<a href="https://colab.research.google.com/github/Dulina77/Spotify_data_analysis/blob/main/SpotifyDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("light_spotify_dataset.csv")
data

,artist,song,emotion,variance,Genre,Release Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
0,ABBA,She's My Kind Of Girl,joy,0.447619,pop,2014,F Maj,128,-6.00,No,31,78,56,60,3,31,7,0
1,ABBA,"Andante, Andante",love,0.202222,pop,1980,A# Maj,102,-10.72,No,59,36,52,38,2,7,68,0
2,ABBA,As Good As New,sadness,0.300881,pop,1979,E Maj,139,-5.70,No,50,78,85,97,3,8,20,2
3,ABBA,Bang,joy,0.355000,pop,1975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
4,ABBA,Bang-A-Boomerang,joy,0.355000,pop,1975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236983,(Eri Sasaki),Gate Of Steiner,sadness,0.833514,"Unknown,Unknown,Unknown",2018,D min,148,-6.44,No,41,61,41,37,4,14,20,0
236984,(Elena Tsagrinou),El Diablo,love,0.833514,"Unknown,Unknown,Unknown",2021,A min,114,-7.78,No,51,66,66,62,13,84,0,0
236985,(Dima Bilan),Believe,joy,0.833514,"Unknown,Unknown,Unknown",2009,C min,134,-6.72,No,36,73,55,24,5,22,5,0
236986,(Ani Lorak),Shady Lady,joy,0.833514,"Unknown,Unknown,Unknown",2009,F# min,128,-13.00,No,37,70,71,77,5,7,5,0
236987,(Alla Pugacheva) & 50 Cent,Позови меня P.I.M.P,anger,0.833514,"Unknown,Unknown,Unknown",2023,B Maj,175,-7.15,No,54,91,42,32,8,38,0,84

In [ ]:
data.columns

Index(['artist', 'song', 'emotion', 'variance', 'Genre', 'Release Date', 'Key',
       'Tempo', 'Loudness', 'Explicit', 'Popularity', 'Energy', 'Danceability',
       'Positiveness', 'Speechiness', 'Liveness', 'Acousticness',
       'Instrumentalness'],
      dtype='object')

In [ ]:
data.describe()

,variance,Release Date,Tempo,Loudness,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
count,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000,236988.000000
mean,0.658932,2008.472826,120.609685,-8.038657,40.003705,62.369166,59.127492,47.656966,11.748042,19.905333,26.156194,5.440052
std,0.320735,14.756158,28.966358,3.842215,18.770245,22.083376,17.069117,23.801800,12.443653,16.551294,29.047331,17.662526
min,-1.000000,1900.000000,33.000000,-46.770000,0.000000,0.000000,6.000000,0.000000,2.000000,1.000000,0.000000,0.000000
25%,0.833514,2002.000000,97.000000,-9.890000,27.000000,48.000000,48.000000,29.000000,4.000000,10.000000,2.000000,0.000000
50%,0.833514,2015.000000,120.000000,-7.190000,39.000000,64.000000,60.000000,47.000000,6.000000,13.000000,14.000000,0.000000
75%,0.833514,2019.000000,140.000000,-5.370000,52.000000,80.000000,72.000000,66.000000,16.000000,25.000000,44.000000,0.000000
max,1.000000,2024.000000,200.000000,3.740000,100.000000,100.000000,99.000000,99.000000,97.000000,100.000000,100.000000,100.000000

In [ ]:
data.dtypes

artist               object
song                 object
emotion              object
variance            float64
Genre                object
Release Date          int64
Key                  object
Tempo                 int64
Loudness            float64
Explicit             object
Popularity            int64
Energy                int64
Danceability          int64
Positiveness          int64
Speechiness           int64
Liveness              int64
Acousticness          int64
Instrumentalness      int64
dtype: object

In [ ]:
data['Release Date'] = pd.to_datetime(data['Release Date'])
data.dtypes

artist                      object
song                        object
emotion                     object
variance                   float64
Genre                       object
Release Date        datetime64[ns]
Key                         object
Tempo                        int64
Loudness                   float64
Explicit                    object
Popularity                   int64
Energy                       int64
Danceability                 int64
Positiveness                 int64
Speechiness                  int64
Liveness                     int64
Acousticness                 int64
Instrumentalness             int64
dtype: object

In [ ]:
data.columns = data.columns.str.replace(" ", "_").str.replace("-", "_")
data

,artist,song,emotion,variance,Genre,Release_Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
0,ABBA,She's My Kind Of Girl,joy,0.447619,pop,1970-01-01 00:00:00.000002014,F Maj,128,-6.00,No,31,78,56,60,3,31,7,0
1,ABBA,"Andante, Andante",love,0.202222,pop,1970-01-01 00:00:00.000001980,A# Maj,102,-10.72,No,59,36,52,38,2,7,68,0
2,ABBA,As Good As New,sadness,0.300881,pop,1970-01-01 00:00:00.000001979,E Maj,139,-5.70,No,50,78,85,97,3,8,20,2
3,ABBA,Bang,joy,0.355000,pop,1970-01-01 00:00:00.000001975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
4,ABBA,Bang-A-Boomerang,joy,0.355000,pop,1970-01-01 00:00:00.000001975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236983,(Eri Sasaki),Gate Of Steiner,sadness,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002018,D min,148,-6.44,No,41,61,41,37,4,14,20,0
236984,(Elena Tsagrinou),El Diablo,love,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002021,A min,114,-7.78,No,51,66,66,62,13,84,0,0
236985,(Dima Bilan),Believe,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002009,C min,134,-6.72,No,36,73,55,24,5,22,5,0
236986,(Ani Lorak),Shady Lady,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002009,F# min,128,-13.00,No,37,70,71,77,5,7,5,0
236987,(Alla Pugacheva) & 50 Cent,Позови меня P.I.M.P,anger,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002023,B Maj,175,-7.15,No,54,91,42,32,8,38,0,84

In [ ]:
data.drop_duplicates()

,artist,song,emotion,variance,Genre,Release_Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
0,ABBA,She's My Kind Of Girl,joy,0.447619,pop,1970-01-01 00:00:00.000002014,F Maj,128,-6.00,No,31,78,56,60,3,31,7,0
1,ABBA,"Andante, Andante",love,0.202222,pop,1970-01-01 00:00:00.000001980,A# Maj,102,-10.72,No,59,36,52,38,2,7,68,0
2,ABBA,As Good As New,sadness,0.300881,pop,1970-01-01 00:00:00.000001979,E Maj,139,-5.70,No,50,78,85,97,3,8,20,2
3,ABBA,Bang,joy,0.355000,pop,1970-01-01 00:00:00.000001975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
4,ABBA,Bang-A-Boomerang,joy,0.355000,pop,1970-01-01 00:00:00.000001975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236983,(Eri Sasaki),Gate Of Steiner,sadness,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002018,D min,148,-6.44,No,41,61,41,37,4,14,20,0
236984,(Elena Tsagrinou),El Diablo,love,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002021,A min,114,-7.78,No,51,66,66,62,13,84,0,0
236985,(Dima Bilan),Believe,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002009,C min,134,-6.72,No,36,73,55,24,5,22,5,0
236986,(Ani Lorak),Shady Lady,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002009,F# min,128,-13.00,No,37,70,71,77,5,7,5,0
236987,(Alla Pugacheva) & 50 Cent,Позови меня P.I.M.P,anger,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002023,B Maj,175,-7.15,No,54,91,42,32,8,38,0,84

In [ ]:
data.isna().sum()

artist              0
song                8
emotion             0
variance            0
Genre               0
Release_Date        0
Key                 0
Tempo               0
Loudness            0
Explicit            0
Popularity          0
Energy              0
Danceability        0
Positiveness        0
Speechiness         0
Liveness            0
Acousticness        0
Instrumentalness    0
dtype: int64

In [ ]:
data[data['song'].isna()]

,artist,song,emotion,variance,Genre,Release_Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
73535,Trippie Redd,NaN,anger,0.833514,rap,1970-01-01 00:00:00.000002017,G Maj,80,-5.06,Yes,20,75,55,37,6,20,0,0
74758,Touch Amor,NaN,sadness,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000001986,C Maj,71,-22.89,No,0,6,41,25,4,6,99,5
89267,Tally Hall,NaN,sadness,0.833514,alternative,1970-01-01 00:00:00.000002005,E Maj,101,-6.68,No,50,78,71,54,28,31,11,0
111099,RATKING,NaN,sadness,0.833514,rap,1970-01-01 00:00:00.000002018,F Maj,121,-4.41,No,30,90,42,29,5,11,0,0
115664,Pinegrove,NaN,anger,0.833514,alternative,1970-01-01 00:00:00.000002015,C# min,77,-8.30,No,81,63,55,21,3,8,1,20
122056,OSHUN,NaN,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002021,G Maj,180,-6.67,No,0,85,63,6,7,10,0,72
190394,Elevation Worship,NaN,joy,0.833514,"Unknown,Unknown,Unknown",1970-01-01 00:00:00.000002023,A Maj,127,-6.72,No,77,87,59,46,7,95,2,0
218249,Billie Eilish,NaN,joy,0.833514,pop,1970-01-01 00:00:00.000002022,C# Maj,101,-11.32,Yes,5,42,66,42,34,17,35,0

In [ ]:
data = data.dropna(subset=['song'])
data.isna().sum()

artist              0
song                0
emotion             0
variance            0
Genre               0
Release_Date        0
Key                 0
Tempo               0
Loudness            0
Explicit            0
Popularity          0
Energy              0
Danceability        0
Positiveness        0
Speechiness         0
Liveness            0
Acousticness        0
Instrumentalness    0
dtype: int64

In [ ]:
data['artist'].value_counts()

artist
Genius English Translations    1604
Lil Wayne                       753
Juice WRLD                      647
Chris Brown                     589
Gucci Mane                      522
                               ...
Soundtrack of Your Life           1
Souly Had & Mac Ayres             1
Soulwax                           1
Soulja Boy & Famous Dex           1
Jona (PH)                         1
Name: count, Length: 30607, dtype: int64

In [ ]:
data['Release_Date'] = data['Release_Date'].astype(str).str[-4:]
data

<ipython-input-50-1ecd30229ac3>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,artist,song,emotion,variance,Genre,Release_Date,Key,Tempo,Loudness,Explicit,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness
0,ABBA,She's My Kind Of Girl,joy,0.447619,pop,2014,F Maj,128,-6.00,No,31,78,56,60,3,31,7,0
1,ABBA,"Andante, Andante",love,0.202222,pop,1980,A# Maj,102,-10.72,No,59,36,52,38,2,7,68,0
2,ABBA,As Good As New,sadness,0.300881,pop,1979,E Maj,139,-5.70,No,50,78,85,97,3,8,20,2
3,ABBA,Bang,joy,0.355000,pop,1975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
4,ABBA,Bang-A-Boomerang,joy,0.355000,pop,1975,F Maj,132,-3.00,No,52,76,50,89,3,32,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236983,(Eri Sasaki),Gate Of Steiner,sadness,0.833514,"Unknown,Unknown,Unknown",2018,D min,148,-6.44,No,41,61,41,37,4,14,20,0
236984,(Elena Tsagrinou),El Diablo,love,0.833514,"Unknown,Unknown,Unknown",2021,A min,114,-7.78,No,51,66,66,62,13,84,0,0
236985,(Dima Bilan),Believe,joy,0.833514,"Unknown,Unknown,Unknown",2009,C min,134,-6.72,No,36,73,55,24,5,22,5,0
236986,(Ani Lorak),Shady Lady,joy,0.833514,"Unknown,Unknown,Unknown",2009,F# min,128,-13.00,No,37,70,71,77,5,7,5,0
236987,(Alla Pugacheva) & 50 Cent,Позови меня P.I.M.P,anger,0.833514,"Unknown,Unknown,Unknown",2023,B Maj,175,-7.15,No,54,91,42,32,8,38,0,84

In [ ]:
import plotly.express as px

In [ ]:
data_grouped_by_date = data.groupby('Release_Date')['song'].nunique().reset_index()


fig = px.bar(
    data_grouped_by_date,
    x = 'Release_Date',
    y = 'song',
    template='presentation'
)

fig.show()

In [ ]:
data_grouped_by_date

   Release_Date   song
0          1900      4
1          1903      1
2          1913      2
3          1926      2
4          1930      2
..          ...    ...
88         2020  12287
89         2021   8824
90         2022   4717
91         2023   5298
92         2024   9303

[93 rows x 2 columns]

In [ ]:
data_grouped_by_artists = data.groupby('artist')['Popularity'].mean().reset_index()
data_grouped_by_artists

                             artist  Popularity
0        (Alla Pugacheva) & 50 Cent   54.000000
1                       (Ani Lorak)   37.000000
2                      (Dima Bilan)   36.000000
3                 (Elena Tsagrinou)   51.000000
4                      (Eri Sasaki)   41.000000
...                             ...         ...
30602                    yvngxchris   42.625000
30603                       yxngxr1   37.076923
30604                         zamir   26.000000
30605           zamir & marc indigo   47.000000
30606                 {Parentheses}   45.000000

[30607 rows x 2 columns]

In [ ]:
figure_2 = px.bar(
    data_grouped_by_artists,
    x = 'artist',
    y = 'Popularity',
    template = 'presentation'
)
figure_2.show()